### PR TITLE
A typo

### PR DESCRIPTION
**Pull request by SnowyHit**
There's a typo on square speed

### CODE REVIEW

**Review by erickzanardo — APPROVED** [review]
Thanks for noticing this! LGTM

**Comment by erickzanardo** [comment]
I just noticed that you sent this PR on the flame_tutorials repository, we have moved the tutorials to the main flame repo, would you mind replicating this PR there?

**Comment by spydon** [comment]
Good catch @GendalfThePink! It will be a merge conflict with the documentation update PR if you update it on the main repository so I put it in here:
https://github.com/flame-engine/flame/pull/732/commits/19e826e1e171d476e860451a176e22dceec18514

**Comment by spydon** [comment]
@erickzanardo we should probably archive this repo?

**Comment by erickzanardo** [comment]
> @erickzanardo we should probably archive this repo?

Yep, we totally should

**Comment by luanpotter** [comment]
Closing as this was merged on the main repo.

**Pull request closed without merging**
